#!/usr/bin/env ruby

#
# Copyright (C) 2014 Noralf Tronnes
#
# MIT License
#

begin
  require 'rubygems'
  gem 'rake'
rescue LoadError
end

require 'pp'
require 'rake'
require_relative 'utils'
require_relative 'application'
require_relative 'dsl'
require_relative 'tasks'
require_relative 'var'
require_relative 'git'
require_relative 'linuxversion'
require_relative 'readme'


# add first in the search path
$LOAD_PATH.unshift ENV["RPI_BUILD_DIR"]

Rake.application = Rake::Rpibuild.new ENV["RPI_BUILD_DIR"], ENV['WORKDIR'], ENV['DOWNLOAD_DIR']
Rake.application.run
